# Generated by Django 2.2.2 on 2019-11-18 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionClima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='Fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
