# Generated by Django 2.2.7 on 2019-11-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionClima', '0002_auto_20191118_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='usuarios'),
        ),
    ]
